// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO1FhywHj5EiHdnhI1Dok-DEVaWLzBLDA',
    appId: '1:911360312920:web:fbebc9d6f42d4af5f5ac2d',
    messagingSenderId: '911360312920',
    projectId: 'whatsapp-clone-a7435',
    authDomain: 'whatsapp-clone-a7435.firebaseapp.com',
    storageBucket: 'whatsapp-clone-a7435.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBO_XycZ90D8aAvzGVTQoOVsiPivVaeeA',
    appId: '1:911360312920:android:7b433a2c4dbcc9eaf5ac2d',
    messagingSenderId: '911360312920',
    projectId: 'whatsapp-clone-a7435',
    storageBucket: 'whatsapp-clone-a7435.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3qJsknEwzmy8Adtldg_5-g_xEa7YNb8c',
    appId: '1:911360312920:ios:8b1995c9db56e6b8f5ac2d',
    messagingSenderId: '911360312920',
    projectId: 'whatsapp-clone-a7435',
    storageBucket: 'whatsapp-clone-a7435.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
